#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.motionrider.com.MotionRiderDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="strahlen_motionrider")]
	public partial class MotionRiderDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void Insertmotion_ride(motion_ride instance);
    partial void Updatemotion_ride(motion_ride instance);
    partial void Deletemotion_ride(motion_ride instance);
    partial void Insertoutlet(outlet instance);
    partial void Updateoutlet(outlet instance);
    partial void Deleteoutlet(outlet instance);
    partial void Insertsale(sale instance);
    partial void Updatesale(sale instance);
    partial void Deletesale(sale instance);
    partial void Insertsales_closing(sales_closing instance);
    partial void Updatesales_closing(sales_closing instance);
    partial void Deletesales_closing(sales_closing instance);
    partial void Insertslush(slush instance);
    partial void Updateslush(slush instance);
    partial void Deleteslush(slush instance);
    partial void Insertslush_items_sale(slush_items_sale instance);
    partial void Updateslush_items_sale(slush_items_sale instance);
    partial void Deleteslush_items_sale(slush_items_sale instance);
    partial void Insertticket_items_sale(ticket_items_sale instance);
    partial void Updateticket_items_sale(ticket_items_sale instance);
    partial void Deleteticket_items_sale(ticket_items_sale instance);
    #endregion
		
		public MotionRiderDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["strahlen_motionriderConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MotionRiderDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MotionRiderDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MotionRiderDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MotionRiderDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<motion_ride> motion_rides
		{
			get
			{
				return this.GetTable<motion_ride>();
			}
		}
		
		public System.Data.Linq.Table<outlet> outlets
		{
			get
			{
				return this.GetTable<outlet>();
			}
		}
		
		public System.Data.Linq.Table<sale> sales
		{
			get
			{
				return this.GetTable<sale>();
			}
		}
		
		public System.Data.Linq.Table<sales_closing> sales_closings
		{
			get
			{
				return this.GetTable<sales_closing>();
			}
		}
		
		public System.Data.Linq.Table<slush> slushes
		{
			get
			{
				return this.GetTable<slush>();
			}
		}
		
		public System.Data.Linq.Table<slush_items_sale> slush_items_sales
		{
			get
			{
				return this.GetTable<slush_items_sale>();
			}
		}
		
		public System.Data.Linq.Table<ticket_items_sale> ticket_items_sales
		{
			get
			{
				return this.GetTable<ticket_items_sale>();
			}
		}
		
		public System.Data.Linq.Table<View_Ticket_DailySale> View_Ticket_DailySales
		{
			get
			{
				return this.GetTable<View_Ticket_DailySale>();
			}
		}
		
		public System.Data.Linq.Table<View_Slush_DailySale> View_Slush_DailySales
		{
			get
			{
				return this.GetTable<View_Slush_DailySale>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _admin_id;
		
		private string _admin_name;
		
		private string _admin_picture;
		
		private string _admin_email;
		
		private string _admin_password;
		
		private string _admin_phone;
		
		private string _admin_address;
		
		private string _admin_city;
		
		private System.Nullable<int> _outlet_id;
		
		private string _admin_comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onadmin_idChanging(int value);
    partial void Onadmin_idChanged();
    partial void Onadmin_nameChanging(string value);
    partial void Onadmin_nameChanged();
    partial void Onadmin_pictureChanging(string value);
    partial void Onadmin_pictureChanged();
    partial void Onadmin_emailChanging(string value);
    partial void Onadmin_emailChanged();
    partial void Onadmin_passwordChanging(string value);
    partial void Onadmin_passwordChanged();
    partial void Onadmin_phoneChanging(string value);
    partial void Onadmin_phoneChanged();
    partial void Onadmin_addressChanging(string value);
    partial void Onadmin_addressChanged();
    partial void Onadmin_cityChanging(string value);
    partial void Onadmin_cityChanged();
    partial void Onoutlet_idChanging(System.Nullable<int> value);
    partial void Onoutlet_idChanged();
    partial void Onadmin_commentChanging(string value);
    partial void Onadmin_commentChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_id", DbType="Int NOT NULL")]
		public int admin_id
		{
			get
			{
				return this._admin_id;
			}
			set
			{
				if ((this._admin_id != value))
				{
					this.Onadmin_idChanging(value);
					this.SendPropertyChanging();
					this._admin_id = value;
					this.SendPropertyChanged("admin_id");
					this.Onadmin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string admin_name
		{
			get
			{
				return this._admin_name;
			}
			set
			{
				if ((this._admin_name != value))
				{
					this.Onadmin_nameChanging(value);
					this.SendPropertyChanging();
					this._admin_name = value;
					this.SendPropertyChanged("admin_name");
					this.Onadmin_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_picture", DbType="VarChar(255)")]
		public string admin_picture
		{
			get
			{
				return this._admin_picture;
			}
			set
			{
				if ((this._admin_picture != value))
				{
					this.Onadmin_pictureChanging(value);
					this.SendPropertyChanging();
					this._admin_picture = value;
					this.SendPropertyChanged("admin_picture");
					this.Onadmin_pictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string admin_email
		{
			get
			{
				return this._admin_email;
			}
			set
			{
				if ((this._admin_email != value))
				{
					this.Onadmin_emailChanging(value);
					this.SendPropertyChanging();
					this._admin_email = value;
					this.SendPropertyChanged("admin_email");
					this.Onadmin_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string admin_password
		{
			get
			{
				return this._admin_password;
			}
			set
			{
				if ((this._admin_password != value))
				{
					this.Onadmin_passwordChanging(value);
					this.SendPropertyChanging();
					this._admin_password = value;
					this.SendPropertyChanged("admin_password");
					this.Onadmin_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_phone", DbType="VarChar(255)")]
		public string admin_phone
		{
			get
			{
				return this._admin_phone;
			}
			set
			{
				if ((this._admin_phone != value))
				{
					this.Onadmin_phoneChanging(value);
					this.SendPropertyChanging();
					this._admin_phone = value;
					this.SendPropertyChanged("admin_phone");
					this.Onadmin_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_address", DbType="VarChar(255)")]
		public string admin_address
		{
			get
			{
				return this._admin_address;
			}
			set
			{
				if ((this._admin_address != value))
				{
					this.Onadmin_addressChanging(value);
					this.SendPropertyChanging();
					this._admin_address = value;
					this.SendPropertyChanged("admin_address");
					this.Onadmin_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_city", DbType="VarChar(255)")]
		public string admin_city
		{
			get
			{
				return this._admin_city;
			}
			set
			{
				if ((this._admin_city != value))
				{
					this.Onadmin_cityChanging(value);
					this.SendPropertyChanging();
					this._admin_city = value;
					this.SendPropertyChanged("admin_city");
					this.Onadmin_cityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outlet_id", DbType="Int")]
		public System.Nullable<int> outlet_id
		{
			get
			{
				return this._outlet_id;
			}
			set
			{
				if ((this._outlet_id != value))
				{
					this.Onoutlet_idChanging(value);
					this.SendPropertyChanging();
					this._outlet_id = value;
					this.SendPropertyChanged("outlet_id");
					this.Onoutlet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_comment", DbType="VarChar(255)")]
		public string admin_comment
		{
			get
			{
				return this._admin_comment;
			}
			set
			{
				if ((this._admin_comment != value))
				{
					this.Onadmin_commentChanging(value);
					this.SendPropertyChanging();
					this._admin_comment = value;
					this.SendPropertyChanged("admin_comment");
					this.Onadmin_commentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.motion_ride")]
	public partial class motion_ride : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _motion_id;
		
		private string _motion_name;
		
		private decimal _motion_charges;
		
		private string _motion_comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onmotion_idChanging(int value);
    partial void Onmotion_idChanged();
    partial void Onmotion_nameChanging(string value);
    partial void Onmotion_nameChanged();
    partial void Onmotion_chargesChanging(decimal value);
    partial void Onmotion_chargesChanged();
    partial void Onmotion_commentChanging(string value);
    partial void Onmotion_commentChanged();
    #endregion
		
		public motion_ride()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motion_id", DbType="Int NOT NULL")]
		public int motion_id
		{
			get
			{
				return this._motion_id;
			}
			set
			{
				if ((this._motion_id != value))
				{
					this.Onmotion_idChanging(value);
					this.SendPropertyChanging();
					this._motion_id = value;
					this.SendPropertyChanged("motion_id");
					this.Onmotion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motion_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string motion_name
		{
			get
			{
				return this._motion_name;
			}
			set
			{
				if ((this._motion_name != value))
				{
					this.Onmotion_nameChanging(value);
					this.SendPropertyChanging();
					this._motion_name = value;
					this.SendPropertyChanged("motion_name");
					this.Onmotion_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motion_charges", DbType="Decimal(10,2) NOT NULL")]
		public decimal motion_charges
		{
			get
			{
				return this._motion_charges;
			}
			set
			{
				if ((this._motion_charges != value))
				{
					this.Onmotion_chargesChanging(value);
					this.SendPropertyChanging();
					this._motion_charges = value;
					this.SendPropertyChanged("motion_charges");
					this.Onmotion_chargesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motion_comment", DbType="VarChar(255)")]
		public string motion_comment
		{
			get
			{
				return this._motion_comment;
			}
			set
			{
				if ((this._motion_comment != value))
				{
					this.Onmotion_commentChanging(value);
					this.SendPropertyChanging();
					this._motion_comment = value;
					this.SendPropertyChanged("motion_comment");
					this.Onmotion_commentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.outlets")]
	public partial class outlet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _outlet_id;
		
		private string _outlet_name;
		
		private string _outlet_address;
		
		private string _outlet_city;
		
		private string _outlet_comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onoutlet_idChanging(int value);
    partial void Onoutlet_idChanged();
    partial void Onoutlet_nameChanging(string value);
    partial void Onoutlet_nameChanged();
    partial void Onoutlet_addressChanging(string value);
    partial void Onoutlet_addressChanged();
    partial void Onoutlet_cityChanging(string value);
    partial void Onoutlet_cityChanged();
    partial void Onoutlet_commentChanging(string value);
    partial void Onoutlet_commentChanged();
    #endregion
		
		public outlet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outlet_id", DbType="Int NOT NULL")]
		public int outlet_id
		{
			get
			{
				return this._outlet_id;
			}
			set
			{
				if ((this._outlet_id != value))
				{
					this.Onoutlet_idChanging(value);
					this.SendPropertyChanging();
					this._outlet_id = value;
					this.SendPropertyChanged("outlet_id");
					this.Onoutlet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outlet_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string outlet_name
		{
			get
			{
				return this._outlet_name;
			}
			set
			{
				if ((this._outlet_name != value))
				{
					this.Onoutlet_nameChanging(value);
					this.SendPropertyChanging();
					this._outlet_name = value;
					this.SendPropertyChanged("outlet_name");
					this.Onoutlet_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outlet_address", DbType="VarChar(255)")]
		public string outlet_address
		{
			get
			{
				return this._outlet_address;
			}
			set
			{
				if ((this._outlet_address != value))
				{
					this.Onoutlet_addressChanging(value);
					this.SendPropertyChanging();
					this._outlet_address = value;
					this.SendPropertyChanged("outlet_address");
					this.Onoutlet_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outlet_city", DbType="VarChar(255)")]
		public string outlet_city
		{
			get
			{
				return this._outlet_city;
			}
			set
			{
				if ((this._outlet_city != value))
				{
					this.Onoutlet_cityChanging(value);
					this.SendPropertyChanging();
					this._outlet_city = value;
					this.SendPropertyChanged("outlet_city");
					this.Onoutlet_cityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outlet_comment", DbType="VarChar(255)")]
		public string outlet_comment
		{
			get
			{
				return this._outlet_comment;
			}
			set
			{
				if ((this._outlet_comment != value))
				{
					this.Onoutlet_commentChanging(value);
					this.SendPropertyChanging();
					this._outlet_comment = value;
					this.SendPropertyChanged("outlet_comment");
					this.Onoutlet_commentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sales")]
	public partial class sale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _sales_id;
		
		private decimal _sales_total_amount;
		
		private System.DateTime _sales_date;
		
		private System.TimeSpan _sales_time;
		
		private string _sales_comment;
		
		private System.Nullable<int> _outlet_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onsales_idChanging(int value);
    partial void Onsales_idChanged();
    partial void Onsales_total_amountChanging(decimal value);
    partial void Onsales_total_amountChanged();
    partial void Onsales_dateChanging(System.DateTime value);
    partial void Onsales_dateChanged();
    partial void Onsales_timeChanging(System.TimeSpan value);
    partial void Onsales_timeChanged();
    partial void Onsales_commentChanging(string value);
    partial void Onsales_commentChanged();
    partial void Onoutlet_idChanging(System.Nullable<int> value);
    partial void Onoutlet_idChanged();
    #endregion
		
		public sale()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sales_id", DbType="Int NOT NULL")]
		public int sales_id
		{
			get
			{
				return this._sales_id;
			}
			set
			{
				if ((this._sales_id != value))
				{
					this.Onsales_idChanging(value);
					this.SendPropertyChanging();
					this._sales_id = value;
					this.SendPropertyChanged("sales_id");
					this.Onsales_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sales_total_amount", DbType="Decimal(10,2) NOT NULL")]
		public decimal sales_total_amount
		{
			get
			{
				return this._sales_total_amount;
			}
			set
			{
				if ((this._sales_total_amount != value))
				{
					this.Onsales_total_amountChanging(value);
					this.SendPropertyChanging();
					this._sales_total_amount = value;
					this.SendPropertyChanged("sales_total_amount");
					this.Onsales_total_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sales_date", DbType="Date NOT NULL")]
		public System.DateTime sales_date
		{
			get
			{
				return this._sales_date;
			}
			set
			{
				if ((this._sales_date != value))
				{
					this.Onsales_dateChanging(value);
					this.SendPropertyChanging();
					this._sales_date = value;
					this.SendPropertyChanged("sales_date");
					this.Onsales_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sales_time", DbType="Time NOT NULL")]
		public System.TimeSpan sales_time
		{
			get
			{
				return this._sales_time;
			}
			set
			{
				if ((this._sales_time != value))
				{
					this.Onsales_timeChanging(value);
					this.SendPropertyChanging();
					this._sales_time = value;
					this.SendPropertyChanged("sales_time");
					this.Onsales_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sales_comment", DbType="VarChar(255)")]
		public string sales_comment
		{
			get
			{
				return this._sales_comment;
			}
			set
			{
				if ((this._sales_comment != value))
				{
					this.Onsales_commentChanging(value);
					this.SendPropertyChanging();
					this._sales_comment = value;
					this.SendPropertyChanged("sales_comment");
					this.Onsales_commentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outlet_id", DbType="Int")]
		public System.Nullable<int> outlet_id
		{
			get
			{
				return this._outlet_id;
			}
			set
			{
				if ((this._outlet_id != value))
				{
					this.Onoutlet_idChanging(value);
					this.SendPropertyChanging();
					this._outlet_id = value;
					this.SendPropertyChanged("outlet_id");
					this.Onoutlet_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sales_closing")]
	public partial class sales_closing : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _closing_id;
		
		private int _closing_start_sales_id;
		
		private int _closing_end_sales_id;
		
		private decimal _closing_total_amount;
		
		private System.DateTime _closing_login_date;
		
		private System.TimeSpan _closing_login_time;
		
		private string _closing_comment;
		
		private System.Nullable<System.DateTime> _closing_logout_date;
		
		private System.Nullable<System.TimeSpan> _closing_logout_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onclosing_idChanging(int value);
    partial void Onclosing_idChanged();
    partial void Onclosing_start_sales_idChanging(int value);
    partial void Onclosing_start_sales_idChanged();
    partial void Onclosing_end_sales_idChanging(int value);
    partial void Onclosing_end_sales_idChanged();
    partial void Onclosing_total_amountChanging(decimal value);
    partial void Onclosing_total_amountChanged();
    partial void Onclosing_login_dateChanging(System.DateTime value);
    partial void Onclosing_login_dateChanged();
    partial void Onclosing_login_timeChanging(System.TimeSpan value);
    partial void Onclosing_login_timeChanged();
    partial void Onclosing_commentChanging(string value);
    partial void Onclosing_commentChanged();
    partial void Onclosing_logout_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onclosing_logout_dateChanged();
    partial void Onclosing_logout_timeChanging(System.Nullable<System.TimeSpan> value);
    partial void Onclosing_logout_timeChanged();
    #endregion
		
		public sales_closing()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_id", DbType="Int NOT NULL")]
		public int closing_id
		{
			get
			{
				return this._closing_id;
			}
			set
			{
				if ((this._closing_id != value))
				{
					this.Onclosing_idChanging(value);
					this.SendPropertyChanging();
					this._closing_id = value;
					this.SendPropertyChanged("closing_id");
					this.Onclosing_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_start_sales_id", DbType="Int NOT NULL")]
		public int closing_start_sales_id
		{
			get
			{
				return this._closing_start_sales_id;
			}
			set
			{
				if ((this._closing_start_sales_id != value))
				{
					this.Onclosing_start_sales_idChanging(value);
					this.SendPropertyChanging();
					this._closing_start_sales_id = value;
					this.SendPropertyChanged("closing_start_sales_id");
					this.Onclosing_start_sales_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_end_sales_id", DbType="Int NOT NULL")]
		public int closing_end_sales_id
		{
			get
			{
				return this._closing_end_sales_id;
			}
			set
			{
				if ((this._closing_end_sales_id != value))
				{
					this.Onclosing_end_sales_idChanging(value);
					this.SendPropertyChanging();
					this._closing_end_sales_id = value;
					this.SendPropertyChanged("closing_end_sales_id");
					this.Onclosing_end_sales_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_total_amount", DbType="Decimal(10,2) NOT NULL")]
		public decimal closing_total_amount
		{
			get
			{
				return this._closing_total_amount;
			}
			set
			{
				if ((this._closing_total_amount != value))
				{
					this.Onclosing_total_amountChanging(value);
					this.SendPropertyChanging();
					this._closing_total_amount = value;
					this.SendPropertyChanged("closing_total_amount");
					this.Onclosing_total_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_login_date", DbType="Date NOT NULL")]
		public System.DateTime closing_login_date
		{
			get
			{
				return this._closing_login_date;
			}
			set
			{
				if ((this._closing_login_date != value))
				{
					this.Onclosing_login_dateChanging(value);
					this.SendPropertyChanging();
					this._closing_login_date = value;
					this.SendPropertyChanged("closing_login_date");
					this.Onclosing_login_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_login_time", DbType="Time NOT NULL")]
		public System.TimeSpan closing_login_time
		{
			get
			{
				return this._closing_login_time;
			}
			set
			{
				if ((this._closing_login_time != value))
				{
					this.Onclosing_login_timeChanging(value);
					this.SendPropertyChanging();
					this._closing_login_time = value;
					this.SendPropertyChanged("closing_login_time");
					this.Onclosing_login_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_comment", DbType="VarChar(255)")]
		public string closing_comment
		{
			get
			{
				return this._closing_comment;
			}
			set
			{
				if ((this._closing_comment != value))
				{
					this.Onclosing_commentChanging(value);
					this.SendPropertyChanging();
					this._closing_comment = value;
					this.SendPropertyChanged("closing_comment");
					this.Onclosing_commentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_logout_date", DbType="Date")]
		public System.Nullable<System.DateTime> closing_logout_date
		{
			get
			{
				return this._closing_logout_date;
			}
			set
			{
				if ((this._closing_logout_date != value))
				{
					this.Onclosing_logout_dateChanging(value);
					this.SendPropertyChanging();
					this._closing_logout_date = value;
					this.SendPropertyChanged("closing_logout_date");
					this.Onclosing_logout_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_logout_time", DbType="Time")]
		public System.Nullable<System.TimeSpan> closing_logout_time
		{
			get
			{
				return this._closing_logout_time;
			}
			set
			{
				if ((this._closing_logout_time != value))
				{
					this.Onclosing_logout_timeChanging(value);
					this.SendPropertyChanging();
					this._closing_logout_time = value;
					this.SendPropertyChanged("closing_logout_time");
					this.Onclosing_logout_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.slush")]
	public partial class slush : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _slush_id;
		
		private string _slush_name;
		
		private decimal _slush_price;
		
		private string _slush_comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onslush_idChanging(int value);
    partial void Onslush_idChanged();
    partial void Onslush_nameChanging(string value);
    partial void Onslush_nameChanged();
    partial void Onslush_priceChanging(decimal value);
    partial void Onslush_priceChanged();
    partial void Onslush_commentChanging(string value);
    partial void Onslush_commentChanged();
    #endregion
		
		public slush()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slush_id", DbType="Int NOT NULL")]
		public int slush_id
		{
			get
			{
				return this._slush_id;
			}
			set
			{
				if ((this._slush_id != value))
				{
					this.Onslush_idChanging(value);
					this.SendPropertyChanging();
					this._slush_id = value;
					this.SendPropertyChanged("slush_id");
					this.Onslush_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slush_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string slush_name
		{
			get
			{
				return this._slush_name;
			}
			set
			{
				if ((this._slush_name != value))
				{
					this.Onslush_nameChanging(value);
					this.SendPropertyChanging();
					this._slush_name = value;
					this.SendPropertyChanged("slush_name");
					this.Onslush_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slush_price", DbType="Decimal(10,2) NOT NULL")]
		public decimal slush_price
		{
			get
			{
				return this._slush_price;
			}
			set
			{
				if ((this._slush_price != value))
				{
					this.Onslush_priceChanging(value);
					this.SendPropertyChanging();
					this._slush_price = value;
					this.SendPropertyChanged("slush_price");
					this.Onslush_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slush_comment", DbType="VarChar(255)")]
		public string slush_comment
		{
			get
			{
				return this._slush_comment;
			}
			set
			{
				if ((this._slush_comment != value))
				{
					this.Onslush_commentChanging(value);
					this.SendPropertyChanging();
					this._slush_comment = value;
					this.SendPropertyChanged("slush_comment");
					this.Onslush_commentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.slush_items_sales")]
	public partial class slush_items_sale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _ss_id;
		
		private int _ss_quantity;
		
		private decimal _ss_unit_price;
		
		private decimal _ss_total_amount;
		
		private int _sales_id;
		
		private int _slush_id;
		
		private string _ss_comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onss_idChanging(int value);
    partial void Onss_idChanged();
    partial void Onss_quantityChanging(int value);
    partial void Onss_quantityChanged();
    partial void Onss_unit_priceChanging(decimal value);
    partial void Onss_unit_priceChanged();
    partial void Onss_total_amountChanging(decimal value);
    partial void Onss_total_amountChanged();
    partial void Onsales_idChanging(int value);
    partial void Onsales_idChanged();
    partial void Onslush_idChanging(int value);
    partial void Onslush_idChanged();
    partial void Onss_commentChanging(string value);
    partial void Onss_commentChanged();
    #endregion
		
		public slush_items_sale()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ss_id", DbType="Int NOT NULL")]
		public int ss_id
		{
			get
			{
				return this._ss_id;
			}
			set
			{
				if ((this._ss_id != value))
				{
					this.Onss_idChanging(value);
					this.SendPropertyChanging();
					this._ss_id = value;
					this.SendPropertyChanged("ss_id");
					this.Onss_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ss_quantity", DbType="Int NOT NULL")]
		public int ss_quantity
		{
			get
			{
				return this._ss_quantity;
			}
			set
			{
				if ((this._ss_quantity != value))
				{
					this.Onss_quantityChanging(value);
					this.SendPropertyChanging();
					this._ss_quantity = value;
					this.SendPropertyChanged("ss_quantity");
					this.Onss_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ss_unit_price", DbType="Decimal(10,2) NOT NULL")]
		public decimal ss_unit_price
		{
			get
			{
				return this._ss_unit_price;
			}
			set
			{
				if ((this._ss_unit_price != value))
				{
					this.Onss_unit_priceChanging(value);
					this.SendPropertyChanging();
					this._ss_unit_price = value;
					this.SendPropertyChanged("ss_unit_price");
					this.Onss_unit_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ss_total_amount", DbType="Decimal(10,2) NOT NULL")]
		public decimal ss_total_amount
		{
			get
			{
				return this._ss_total_amount;
			}
			set
			{
				if ((this._ss_total_amount != value))
				{
					this.Onss_total_amountChanging(value);
					this.SendPropertyChanging();
					this._ss_total_amount = value;
					this.SendPropertyChanged("ss_total_amount");
					this.Onss_total_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sales_id", DbType="Int NOT NULL")]
		public int sales_id
		{
			get
			{
				return this._sales_id;
			}
			set
			{
				if ((this._sales_id != value))
				{
					this.Onsales_idChanging(value);
					this.SendPropertyChanging();
					this._sales_id = value;
					this.SendPropertyChanged("sales_id");
					this.Onsales_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slush_id", DbType="Int NOT NULL")]
		public int slush_id
		{
			get
			{
				return this._slush_id;
			}
			set
			{
				if ((this._slush_id != value))
				{
					this.Onslush_idChanging(value);
					this.SendPropertyChanging();
					this._slush_id = value;
					this.SendPropertyChanged("slush_id");
					this.Onslush_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ss_comment", DbType="VarChar(255)")]
		public string ss_comment
		{
			get
			{
				return this._ss_comment;
			}
			set
			{
				if ((this._ss_comment != value))
				{
					this.Onss_commentChanging(value);
					this.SendPropertyChanging();
					this._ss_comment = value;
					this.SendPropertyChanged("ss_comment");
					this.Onss_commentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ticket_items_sales")]
	public partial class ticket_items_sale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _ts_id;
		
		private int _ts_quantity;
		
		private decimal _ts_unit_price;
		
		private decimal _ts_total_amount;
		
		private int _motion_id;
		
		private int _sales_id;
		
		private string _ts_comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onts_idChanging(int value);
    partial void Onts_idChanged();
    partial void Onts_quantityChanging(int value);
    partial void Onts_quantityChanged();
    partial void Onts_unit_priceChanging(decimal value);
    partial void Onts_unit_priceChanged();
    partial void Onts_total_amountChanging(decimal value);
    partial void Onts_total_amountChanged();
    partial void Onmotion_idChanging(int value);
    partial void Onmotion_idChanged();
    partial void Onsales_idChanging(int value);
    partial void Onsales_idChanged();
    partial void Onts_commentChanging(string value);
    partial void Onts_commentChanged();
    #endregion
		
		public ticket_items_sale()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts_id", DbType="Int NOT NULL")]
		public int ts_id
		{
			get
			{
				return this._ts_id;
			}
			set
			{
				if ((this._ts_id != value))
				{
					this.Onts_idChanging(value);
					this.SendPropertyChanging();
					this._ts_id = value;
					this.SendPropertyChanged("ts_id");
					this.Onts_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts_quantity", DbType="Int NOT NULL")]
		public int ts_quantity
		{
			get
			{
				return this._ts_quantity;
			}
			set
			{
				if ((this._ts_quantity != value))
				{
					this.Onts_quantityChanging(value);
					this.SendPropertyChanging();
					this._ts_quantity = value;
					this.SendPropertyChanged("ts_quantity");
					this.Onts_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts_unit_price", DbType="Decimal(10,2) NOT NULL")]
		public decimal ts_unit_price
		{
			get
			{
				return this._ts_unit_price;
			}
			set
			{
				if ((this._ts_unit_price != value))
				{
					this.Onts_unit_priceChanging(value);
					this.SendPropertyChanging();
					this._ts_unit_price = value;
					this.SendPropertyChanged("ts_unit_price");
					this.Onts_unit_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts_total_amount", DbType="Decimal(10,2) NOT NULL")]
		public decimal ts_total_amount
		{
			get
			{
				return this._ts_total_amount;
			}
			set
			{
				if ((this._ts_total_amount != value))
				{
					this.Onts_total_amountChanging(value);
					this.SendPropertyChanging();
					this._ts_total_amount = value;
					this.SendPropertyChanged("ts_total_amount");
					this.Onts_total_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motion_id", DbType="Int NOT NULL")]
		public int motion_id
		{
			get
			{
				return this._motion_id;
			}
			set
			{
				if ((this._motion_id != value))
				{
					this.Onmotion_idChanging(value);
					this.SendPropertyChanging();
					this._motion_id = value;
					this.SendPropertyChanged("motion_id");
					this.Onmotion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sales_id", DbType="Int NOT NULL")]
		public int sales_id
		{
			get
			{
				return this._sales_id;
			}
			set
			{
				if ((this._sales_id != value))
				{
					this.Onsales_idChanging(value);
					this.SendPropertyChanging();
					this._sales_id = value;
					this.SendPropertyChanged("sales_id");
					this.Onsales_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts_comment", DbType="VarChar(255)")]
		public string ts_comment
		{
			get
			{
				return this._ts_comment;
			}
			set
			{
				if ((this._ts_comment != value))
				{
					this.Onts_commentChanging(value);
					this.SendPropertyChanging();
					this._ts_comment = value;
					this.SendPropertyChanged("ts_comment");
					this.Onts_commentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Ticket_DailySales")]
	public partial class View_Ticket_DailySale
	{
		
		private int _closing_id;
		
		private int _closing_start_sales_id;
		
		private int _closing_end_sales_id;
		
		private System.Nullable<decimal> _TotalAmount;
		
		private System.DateTime _closing_login_date;
		
		private System.TimeSpan _closing_login_time;
		
		private System.Nullable<System.DateTime> _closing_logout_date;
		
		private System.Nullable<System.TimeSpan> _closing_logout_time;
		
		public View_Ticket_DailySale()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_id", DbType="Int NOT NULL")]
		public int closing_id
		{
			get
			{
				return this._closing_id;
			}
			set
			{
				if ((this._closing_id != value))
				{
					this._closing_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_start_sales_id", DbType="Int NOT NULL")]
		public int closing_start_sales_id
		{
			get
			{
				return this._closing_start_sales_id;
			}
			set
			{
				if ((this._closing_start_sales_id != value))
				{
					this._closing_start_sales_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_end_sales_id", DbType="Int NOT NULL")]
		public int closing_end_sales_id
		{
			get
			{
				return this._closing_end_sales_id;
			}
			set
			{
				if ((this._closing_end_sales_id != value))
				{
					this._closing_end_sales_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				if ((this._TotalAmount != value))
				{
					this._TotalAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_login_date", DbType="Date NOT NULL")]
		public System.DateTime closing_login_date
		{
			get
			{
				return this._closing_login_date;
			}
			set
			{
				if ((this._closing_login_date != value))
				{
					this._closing_login_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_login_time", DbType="Time NOT NULL")]
		public System.TimeSpan closing_login_time
		{
			get
			{
				return this._closing_login_time;
			}
			set
			{
				if ((this._closing_login_time != value))
				{
					this._closing_login_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_logout_date", DbType="Date")]
		public System.Nullable<System.DateTime> closing_logout_date
		{
			get
			{
				return this._closing_logout_date;
			}
			set
			{
				if ((this._closing_logout_date != value))
				{
					this._closing_logout_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_logout_time", DbType="Time")]
		public System.Nullable<System.TimeSpan> closing_logout_time
		{
			get
			{
				return this._closing_logout_time;
			}
			set
			{
				if ((this._closing_logout_time != value))
				{
					this._closing_logout_time = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Slush_DailySales")]
	public partial class View_Slush_DailySale
	{
		
		private int _closing_id;
		
		private int _closing_start_sales_id;
		
		private int _closing_end_sales_id;
		
		private System.Nullable<decimal> _TotalAmount;
		
		private System.DateTime _closing_login_date;
		
		private System.TimeSpan _closing_login_time;
		
		private System.Nullable<System.DateTime> _closing_logout_date;
		
		private System.Nullable<System.TimeSpan> _closing_logout_time;
		
		public View_Slush_DailySale()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_id", DbType="Int NOT NULL")]
		public int closing_id
		{
			get
			{
				return this._closing_id;
			}
			set
			{
				if ((this._closing_id != value))
				{
					this._closing_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_start_sales_id", DbType="Int NOT NULL")]
		public int closing_start_sales_id
		{
			get
			{
				return this._closing_start_sales_id;
			}
			set
			{
				if ((this._closing_start_sales_id != value))
				{
					this._closing_start_sales_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_end_sales_id", DbType="Int NOT NULL")]
		public int closing_end_sales_id
		{
			get
			{
				return this._closing_end_sales_id;
			}
			set
			{
				if ((this._closing_end_sales_id != value))
				{
					this._closing_end_sales_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				if ((this._TotalAmount != value))
				{
					this._TotalAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_login_date", DbType="Date NOT NULL")]
		public System.DateTime closing_login_date
		{
			get
			{
				return this._closing_login_date;
			}
			set
			{
				if ((this._closing_login_date != value))
				{
					this._closing_login_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_login_time", DbType="Time NOT NULL")]
		public System.TimeSpan closing_login_time
		{
			get
			{
				return this._closing_login_time;
			}
			set
			{
				if ((this._closing_login_time != value))
				{
					this._closing_login_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_logout_date", DbType="Date")]
		public System.Nullable<System.DateTime> closing_logout_date
		{
			get
			{
				return this._closing_logout_date;
			}
			set
			{
				if ((this._closing_logout_date != value))
				{
					this._closing_logout_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_logout_time", DbType="Time")]
		public System.Nullable<System.TimeSpan> closing_logout_time
		{
			get
			{
				return this._closing_logout_time;
			}
			set
			{
				if ((this._closing_logout_time != value))
				{
					this._closing_logout_time = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
