//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionRider.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Printing : global::System.Configuration.ApplicationSettingsBase {
        
        private static Printing defaultInstance = ((Printing)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Printing())));
        
        public static Printing Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsDoublePrintEnabled {
            get {
                return ((bool)(this["IsDoublePrintEnabled"]));
            }
            set {
                this["IsDoublePrintEnabled"] = value;
            }
        }
    }
}
